import { SeoHead } from '../components/seo/SeoHead';
import { ArchitecturalVisual } from '../components/ui/ArchitecturalVisual';
import { Button } from '../components/ui/Button';
import { Container } from '../components/ui/Container';
import { CTASection } from '../components/ui/CTASection';
import { InternalHero } from '../components/ui/InternalHero';

export function AboutPage() {
  return <><SeoHead title="Sobre Alvar Consultores Inmobiliarios" description="Más de 18 años de experiencia profesional acumulada y un enfoque cercano para operaciones inmobiliarias en Madrid y su zona sur." path="/nosotros" /><InternalHero eyebrow="NOSOTROS" title={<>Experiencia para decidir.<br /><em>Cercanía para acompañarte.</em></>} text="Una consultora inmobiliaria orientada a hacer comprensibles las decisiones importantes." aside={<div className="big-stat"><strong>18+</strong><span>años de experiencia acumulada</span></div>} /><section className="story-section section-pad"><Container className="story-section__grid"><ArchitecturalVisual variant="facade" label="Composición editorial sobre arquitectura y vivienda" /><div><p className="eyebrow">NUESTRA FORMA DE TRABAJAR</p><h2>Conocimiento del mercado.<br /><em>Seguimiento personal.</em></h2><p>Alvar Consultores Inmobiliarios reúne más de 18 años de experiencia profesional acumulada en el sector. La sociedad se constituyó en 2016, consolidando una trayectoria previa ligada a la intermediación y el asesoramiento inmobiliario.</p><p>Trabajamos con propietarios, compradores e inversores que necesitan una lectura clara de la operación, una negociación bien planteada y seguimiento durante los trámites.</p><Button to="/contacto">Hablar con nosotros</Button></div></Container></section><section className="values-section section-pad"><Container><p className="eyebrow">VALORES</p><div className="values-grid">{[['01','Profesionalidad','Criterio y preparación en cada fase.'],['02','Cercanía','Comunicación directa y comprensible.'],['03','Transparencia','Información clara para decidir con seguridad.'],['04','Compromiso','Seguimiento hasta completar la operación.']].map(([n,t,p]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></Container></section><CTASection /></>;
}
