import { ContactForm } from '../components/forms/ContactForm';
import { SeoHead } from '../components/seo/SeoHead';
import { Container } from '../components/ui/Container';
import { InternalHero } from '../components/ui/InternalHero';
import { business } from '../data/business';

export function ContactPage() {
  return <><SeoHead title="Contacto | Alvar Consultores Inmobiliarios Madrid" description="Habla con Alvar Consultores Inmobiliarios sobre compra, venta, alquiler o inversión en Madrid y su zona sur." path="/contacto" /><InternalHero eyebrow="CONTACTO" title={<>Hablemos de<br /><em>tu operación.</em></>} text="Explícanos qué necesitas y estudiaremos contigo la forma más clara de abordarlo." aside={<span className="internal-hero__quote">Madrid · Pinto · Móstoles</span>} /><section className="contact-page section-pad"><Container className="contact-page__grid"><div className="contact-data"><p className="eyebrow">DATOS DE CONTACTO</p><h2>{business.name}</h2><address><p>{business.addressLine1}<br />{business.addressLine2}<br />{business.postalAddress}</p></address><div><span>Oficina</span><a href={`tel:${business.phoneOfficeHref}`}>{business.phoneOffice}</a></div><div><span>Móvil comercial</span><a href={`tel:${business.phoneMobileHref}`}>{business.phoneMobile}</a></div><div><span>Redes</span><a href={business.instagramUrl} target="_blank" rel="noreferrer">{business.instagram} ↗</a><a href={business.tiktokUrl} target="_blank" rel="noreferrer">{business.tiktok} ↗</a></div><div className="map-placeholder" role="img" aria-label="Referencia territorial de la oficina en Ríos Rosas, Madrid"><span className="map-placeholder__road map-placeholder__road--one" /><span className="map-placeholder__road map-placeholder__road--two" /><span className="map-placeholder__pin">42</span><p>Ríos Rosas · Madrid</p></div></div><div className="contact-page__form"><p className="eyebrow">ENVÍANOS UNA CONSULTA</p><ContactForm /></div></Container></section></>;
}
